import { getProviders, signIn as SignIntoProvider } from "next-auth/react";
import Header from "../../components/Header";
import Head from "next/head";

//Browser level
function signIn({providers}) {
    return (
        <>
            <Head>
                <title>Instagram SignIn</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
                <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
                <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
                <link rel="manifes" href="/site.webmanifest" />
                <meta name="msapplication-TileColor" content="#da532c" />
                <meta name = "theme-color" content="#ffffff" />



            </Head>
             <Header />
             <div className="flex flex-col items-center justify-center min-h-screen py-2 -mt-56 px-14 text-center"> 
                <img className="w-80" src = "https://links.papareact.com/ocw" alt = "" />
                <p className = "font-xs italic">
                    Not a real app, built only for portfolio building and demonstration purposes only
                </p>
              <div className="mt-40">
                {Object.values(providers).map((provider) => (
                    <div key={provider.name}>
                        <button 
                            className="p-3 bg-blue-500 rounded-lg text-white"
                            onClick = {() => SignIntoProvider(provider.id, {callbackUrl: "/"})}
                        >
                            Sign in with {provider.name}
                        </button>
                    </div>
                ))}
              </div>
             </div> 
        </> 
    );
}


//Server side render
export async function getServerSideProps(){
    const providers = await getProviders();

    return {
        props: {
            providers
        }
    }
}
export default signIn;